### ISSUE TITLE
Can you upload bin files to Releases ?

### ISSUE THREAD

**Issue by kazmat6502** [ClusterM/fdskey#1]
I want to build fdskey, but no knowledge about stm32.

**Comment by ClusterM** [comment]
Hi.

It's still under development, I'll make release soon.
You can download interim builds there: https://clusterm.github.io/fdskey/

**Comment by kazmat6502** [comment]
Thanks !!!

**Comment by kazmat6502** [comment]
Thank you very much. It worked fine. Personally, I would like to support GAME DOCTOR format files like FDSSTICK.
