### ISSUE TITLE
CPL File

### ISSUE THREAD

**Issue by Radeon91** [ClusterM/fdskey#10]
Please could you update CPL file?
I want to make it but my welding skills are not very good, I would like to order them already welded.

Thanks

**Comment by ClusterM** [comment]
What is CPL file? 😮

**Comment by ClusterM** [comment]
Try this: [fdskey.csv](https://github.com/ClusterM/fdskey/files/12302885/fdskey.csv)
Also, you can buy already assembled device on AliExpress: https://www.aliexpress.us/item/3256805697532063.html
And other sites.
