### ISSUE TITLE
Programming Issue Using ST-Link-V2 - Read Out Protection Error.

### ISSUE THREAD

**Issue by PercyRosasR** [ClusterM/fdskey#12]
First of all, thanks for all the effort in this project, thanks to ClusterM for creating this.

I have made 2 unids following all the instructions on the FdsKey principal page, I am having some issues with the connection and programming the STM32G0B0CET6 chip.

I use the ST-Link-V2 Clone, with STM32-ST-Link-Utility, this is because is the only way I had to connect the board via stlink.

1.- Using STM32-ST-Link Utility

![image](https://github.com/ClusterM/fdskey/assets/135164149/3107af22-10d8-4d42-a04f-b2b10eb4b5d0)

23:41:12 : ST-LINK SN : 700039000F0000315151524E
23:41:12 : V2J42S7
23:41:12 : Connected via SWD.
23:41:12 : SWD Frequency = 4,0 MHz.
23:41:12 : Connection mode : HotPlug.
23:41:12 : Debug in Low Power mode enabled.
23:41:12 : Device ID:0x467 
23:41:12 : Device family :Unknown device

My first question is, if this Device family information is correct?

2.- When I try to program the chip using the bootloader bin fie, this issue happens:

![image](https://github.com/ClusterM/fdskey/assets/135164149/5e37ad7a-2e61-451b-850c-37419c6fb024)

![image](https://github.com/ClusterM/fdskey/assets/135164149/da26c7e1-6862-485e-8eb1-89604bef9ed0)

Pressing the ok button , the next error appears.

![image](https://github.com/ClusterM/fdskey/assets/135164149/bda8541b-1aa2-459c-9803-f6459028aae5)

![image](https://github.com/ClusterM/fdskey/assets/135164149/90f56cb8-3978-4e1f-8a48-baa65a37c9c4)

![image](https://github.com/ClusterM/fdskey/assets/135164149/353c0fb8-acd5-4b4d-b041-e7c0f8979799)

Do you have any clue or advice to solve this problem?

I have already try to disable the Read out protection, but I got this issue after applying.

![image](https://github.com/ClusterM/fdskey/assets/135164149/d170c590-6d57-45b4-a6ab-4e978944fcf3)
![image](https://github.com/ClusterM/fdskey/assets/135164149/a07c9359-bd28-4147-97ac-1a53277ed98a)

3.- Also want to explain, why I'm not using the STM32Cubeprogrammer.

This is because when I connect my stlink32 in the combo box Serial Number, i got the letter P in both of my boards.

![image](https://github.com/ClusterM/fdskey/assets/135164149/c4586fb7-6e56-469f-9ecc-5a10570e21ed)

and when I change the Shared combo to Enable, I got this, and I am not able to connect the device in any way.
![image](https://github.com/ClusterM/fdskey/assets/135164149/4ed40f42-ec53-4275-846a-b921e2cec06d)

I hope you can help me with this issue.

Thanks for all in advance and greetings from Peru.

**Comment by ClusterM** [comment]
Hi! The STM32-ST-Link Utility will not work :( It doesn't recognize this microcontroller (it's a new model). I don't know why STM32CubeProgrammer has such weird behavior, but you need to use it. Please try the CLI version:

```
STM32_Programmer_CLI.exe -c port=SWD --erase all --download bootloader.bin 0x08000000 --download fdskey.bin 0x08020000
```

**Comment by PercyRosasR** [comment]
Hi Alexey, 

you are completely right. The old stlink software does not allow me to complete the programming(connects but gives the lock error).

The cube software has a different problem.

The solution you gave is the correct one, by cmd and the command I was able to program my chips.

Now I'm having a different issue I will open a new topic, to close this one.

Thanks in advance for your help.

**Comment by partlyhuman** [comment]
Thank you! Issues flashing the STM32 aborted my efforts to build the FDSkey last year. This new instruction worked perfectly for me the first time.

FYI if you're on MacOS, you can find the CLI at
```
/Applications/STMicroelectronics/STM32Cube/STM32CubeProgrammer/STM32CubeProgrammer.app/Contents/MacOs/bin/STM32_Programmer_CLI
```
assuming the default installation.
