### ISSUE TITLE
Unable to load any dump

### ISSUE THREAD

**Issue by LucentW** [ClusterM/fdskey#20]
Hey,
I got ahold of one of the prebuilt FDSKey PCBs off AliExpress, it turns on regularly, I am able to select a dump off the SD card, it signals correctly to the RAM adapter a disk was inserted, but it indefinitely loops around the disk, the FDS BIOS staying stuck on the "now loading" screen (never passing KYODAKU/no black screen before the copyright notice).

I tried already updating to the interim build (both bootloader and software), changing microSD card, using different RAM adapters (both work perfectly fine with my FDS drive) and reflowing all components. I also checked the two resistors on the board, since testing caps while in circuit is not really a good test, and they respect the BOM (both 1.5k).

What could be the issue? Which connections should I check?

Thank you very much in advance ;-)

**Comment by LucentW** [comment]
Figured out that the via for READ_DATA was open potentially due to a PCB manufacturing error, I just ordered another prebuilt from another seller and called it a day. Sorry for the hassle :)

**Comment by ClusterM** [comment]
Hi. Sorry for not so fast answer. Ok :)
