### ISSUE TITLE
Error: 02

### ISSUE THREAD

**Issue by williamgentry12** [ClusterM/fdskey#9]
If i get the following error code: 02

Does this mean something is faulty with the FDSKey hardware, maybe broken solder joint on the STM32 chip?

Err. 02 = No disk power supply — batteries and/or AC adaptor.

**Comment by ClusterM** [comment]
Hi! Can you try interim firmware version? http://clusterm.github.io/fdskey/
Put fdskey.bin file on a microSD card and hold all four buttons during power-on to update the firmware.
If problem persists it's hardware problem on MOTOR_ON pin (shorted to ground?).

**Comment by williamgentry12** [comment]
Thank you, I will try :)

**Comment by kingtreelo** [comment]
i was having the exact same issue and this has fixed the issue for me

**Comment by williamgentry12** [comment]
works for me too

**Comment by ClusterM** [comment]
I'll add this fix to release. Thank you for bugreport!

**Comment by kingtreelo** [comment]
this issue seems to have come back on my device, tried flashing it again and still getting the same error

**Comment by ClusterM** [comment]
> this issue seems to have come back on my device, tried flashing it again and still getting the same error

:( Please try this firmware: https://cluster.wtf/temp/FdsKey.bin

But it's not normal. Looks like some hardware problem on line MOTOR_ON.

**Comment by ClusterM** [comment]
Any news?

**Comment by kingtreelo** [comment]
Just tested on 2 of my Famicoms, all looks good so far, will report back once it has been powered off a while, i'll update it in a few hours

**Comment by kingtreelo** [comment]
Looking good still today

**Comment by ClusterM** [comment]
Great, I'll include this in the next version.
